home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.index,name=('index')),
    path('about/',views.about,name=('about')),
    path('contact/',views.contact,name=('contact')),

    path('category/',views.category,name='category'),
    path('product/<str:id>/<slug:slug>',views.product_list,name='product_list'),
    path('product-details/<str:id>/<slug:slug>',views.product_details,name='prod_details')
]

order/urls.py
from django.urls import path 
from . import views


app_name = 'order'

urlpatterns = [
    path('',views.order,name='order'),
    path('addtoshopcart/',views.addtoshopcart,name='addtoshopcart'),
    path('shopcart/',views.shopcart,name='shopcart'),
    path('updatequantity/',views.updatequantity,name='updatequantity'),
    path('deletefromcart/<str:id>',views.deletefromcart,name='deletefromcart'),
    path('checkout/',views.checkout,name='checkout'),
    path('placeorder/',views.placeorder,name='placeorder'),
    path('ordercompleted/',views.ordercompleted,name='ordercompleted')
]

prodigiousapp/urls.py
from user.forms import RegisterForm
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static

from user import views as UserViews
urlpatterns = [
    path('',include('home.urls')),
    path('product/',include('product.urls')),
    path('user/',include('user.urls')),
    path('accountform/', UserViews.accountform, name='accountform'),
    path('login/', UserViews.loginform, name='loginform'),
    path('logout/', UserViews.logoutfunc,name='logoutfunc'),
    path('register/', UserViews.registerform,name='registerform'),
    path('update/', UserViews.userupdate, name='userupdate'),
    path('password/', UserViews.userpassword,name='userpassword'),
    path('order/',include('order.urls')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.product,name='product'),
]

home/models.py
from django.db import models

from django.forms import Textarea, TextInput
from django.forms import ModelForm
from ckeditor_uploader.fields import RichTextUploadingField
# Create your models here.
class Setting(models.Model):
    STATUS =(
        ('True','True'),
        ('False','False'),
    )

    title = models.CharField(max_length=100)
    keywords = models.CharField(max_length=255)
    description = models.CharField(max_length=255, null=True)
    company = models.CharField(max_length=255,null=True)
    address = models.CharField(max_length=100)
    phone = models.CharField(max_length=100, null=True)
    email = models.CharField(max_length=100, blank=True)
    icon = models.ImageField(blank=True, null=True, upload_to='images/')
    logo = models.ImageField(blank=True, null=True, upload_to='images/')
    cart_icon = models.ImageField(blank=True, null=True, upload_to='images/')
    menu_icon = models.ImageField(blank=True, null=True, upload_to='images/')
    facebook = models.CharField(blank=True, max_length=100)
    instargram = models.CharField(blank=True, max_length=100)
    twitter = models.CharField(blank=True, max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    about = RichTextUploadingField(blank=True)
    contact = RichTextUploadingField(blank=True)
    status = models.CharField(max_length=10,choices=STATUS)
    banner_text = RichTextUploadingField(default='what we do')

    def __str__(self):
        return self.title

class Brands(models.Model):
    title = models.CharField(max_length=10,blank=True,null=True)
    brands = models.ImageField(blank=True,null=True,upload_to='images/')

    def __str__(self):
        return self.title
    
class Testimonials(models.Model):
    title = models.CharField(max_length=10,blank=True,null=True)
    comment = models.CharField(max_length=250,blank=True,null=True,default='Thumbs up prodigious store')
    testimonials = models.ImageField(blank=True,null=True,upload_to='images/')

    def __str__(self):
        return self.title

class ContactMessage(models.Model):
    STATUS =(
        ('New','New'),
        ('Read','Read'),
        ('pending','pending'),
        ('Closed','Closed'),
    )

    name = models.CharField(blank=True,max_length=20)
    email = models.CharField(blank=True, max_length=50)
    subject = models.CharField(blank=True,max_length=50)
    message = models.CharField(blank=True, max_length=225)
    status = models.CharField(choices=STATUS, default='New', max_length=10)
    note = models.CharField(blank=True, max_length=100)
    created_at = models.DateTimeField(auto_now_add =True)

    def __str__(self):
        return self.name
    

class ContactForm(ModelForm):
    class Meta:
        model = ContactMessage
        fields = ['name','email','subject','message']    

product/models.py
from django.db import models
from django.contrib.auth.models import User
from django.forms import ModelForm


from django.urls import reverse
from django.utils.safestring import mark_safe
from ckeditor_uploader.fields import RichTextUploadingField


# Create your models here.
class Category(models.Model):
    STATUS =(
        ('True','True'),
        ('False','False'),
    )
    title = models.CharField(max_length=150)
    image = models.ImageField(blank=True, upload_to='images/')
    status = models.CharField(max_length=10, choices=STATUS)
    slug = models.SlugField(null=False, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title
    

    def get_absolute_url(self):
        return reverse("catetory_details", kwargs={"slug": self.slug})
    

class Product(models.Model):
    STATUS=(
        ('True','True'),
        ('False','False'),
    )
    AVAILABLE =(
        ('In Stock','In Stock'),
        ('Out of Stock', 'Out of Stock'),
        ('Restacked','Restocked'),
    )

    category = models.ForeignKey(Category, on_delete=models.DO_NOTHING)
    title = models.CharField(max_length=150, blank=True,)
    keywords = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    image = models.ImageField(blank=True, upload_to='images/')
    price = models.FloatField(blank=True, null=True)
    sizes = models.CharField(max_length=50, null=True, default='Large')
    discount_price = models.FloatField(blank=True, null=True)
    available = models.CharField(choices=AVAILABLE,max_length=20,default='In Stock')
    quantity_instock = models.IntegerField(blank=True, null=True, default=1000)
    minquantity = models.IntegerField(blank=True)
    amount = models.IntegerField(blank=True, null=True)
    status = models.CharField(max_length=10, choices=STATUS)
    slug = models.SlugField(null=False, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    featured = models.BooleanField(blank=True)
    latest = models.BooleanField(blank=True)
    banner = models.BooleanField(blank=True)
    offer = models.BooleanField(blank=True)
    detail = RichTextUploadingField()

    
    def __str__(self):
        return self.title
    

    def image_tag(self):
        return mark_safe('<img src="()" height="50px"/>'.format(self.image.url))

    image_tag.short_description = 'image'

    def get_absolute_url(self):
        return reverse("category_details", kwargs={"slug": self.slug})


class Images(models.Model):
    product = models.ForeignKey(Product,on_delete=models.DO_NOTHING,blank=True)
    image = models.ImageField(blank=True, upload_to='images/')
    

home/views.py
from django.core import paginator
from product.models import Product
from django.shortcuts import redirect, render
from django.http import HttpResponse
from django.contrib import messages
from django.core.paginator import EmptyPage,PageNotAnInteger,Paginator
from user.models import UserProfile

from.models import *
from product.models import *
# from user.models import Userprofile


# Create your views here.
def index(request):
    setting = Setting.objects.get(pk=1)
    brands = Brands.objects.all()
    banner = Product.objects.get(banner=True)
    offer = Product.objects.get(offer=True)
    category = Category.objects.all()[:3]
    featured = Product.objects.filter(featured=True)
    latest = Product.objects.filter(latest=True)[:4]
    latest2 = Product.objects.filter(latest=True).order_by('-id')[:4]
    testimonials = Testimonials.objects.all()
    context ={
        'setting':setting,
        'brands':brands,
        'banner':banner,
        'offer':offer,
        'category':category,
        'featured':featured,
        'latest':latest,
        'latest2':latest2,
        'testimonials':testimonials,
    }
    return render(request, 'index.html',context)

def about(request):
    setting = Setting.objects.get(pk=1)
    testimonials = Testimonials.objects.all()
    context={
        'setting':setting,
        'testimonials':testimonials,
    }
    
    return render(request,'about.html',context)
    


def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request,'Your message has been sent! our customer serverce Team would be with you shortly')
            return redirect('/contact')

    setting = Setting.objects.get(pk=1)
    form = ContactForm
    brands = Brands.objects.all()
    category = Category.objects.all()

    context={
        'setting':setting,
        'form':form,
        'brands': brands,
        'category': category,
    }
    
    return render(request,'contact.html',context)


def category(request):
    setting = Setting.objects.get(pk=1)
    brands = Brands.objects.all()
    offer = Product.objects.get(offer=True)
    category = Category.objects.order_by('-created_at').filter(status=True)
    paginator = Paginator(category,4)
    page = request.GET.get('page')
    paged_category = paginator.get_page(page)

    
    context= {
        'setting':setting,
        'brands': brands,
        'offer':offer,
        'category':  paged_category,
    }

    return render(request, 'category.html',context)

def product_list(request,id,slug):
    setting = Setting.objects.get(pk=1)
    category = Category.objects.all()
    catdata = Category.objects.get(pk=id)
    products = Product.objects.filter(category__id=id)
    paginator = Paginator(products,4)
    page = request.GET.get('page')
    paged_products = paginator.get_page(page)
    


    context={
        'setting':setting,
        'category':category,
        'catdata':catdata,
        'products':paged_products,
    }
    return render(request,'product.html',context)

def product_details(request,id,slug):
    setting = Setting.objects.get(pk=1)
    category = Category.objects.all()
    products = Product.objects.filter(category__id=id)
    product = Product.objects.get(pk=id)
    images = Images.objects.filter(product_id=id)


    context={
        'setting':setting,
        'category':category,
        'products':products,
        'product':product,
        'images':images,
    }

    return render(request,'product-details.html',context)

product/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.

def product(request):
    return HttpResponse('Hey world')
    # return render(request,'index.html')

home/templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block title %} About Us|{{setting.title}}{% endblock title %}
{% block keywords %} {{setting.keywords}} {% endblock keywords %}
{% block description %} {{setting.description}} {% endblock description %}

    <!-- header and banner combinned  -->
    {% block header %} {% include 'header.html' %} {% endblock header %}
    <!-- header done  -->

    {% block content %}
      <!-- Account page  -->
        <div class="account-page">
            <div class="container">
                <div class="row">
                    <div class="col-2">
                        {{setting.about|safe}}
                    </div>
                    <div class="col-2">
                        {{setting.about|safe}}
                    </div>
                </div>
            </div>
        </div>
        <!-- Account page done  -->
    {% endblock content %}
    

    <!-- testimonial  -->
    {% block testimonial %} {% include 'testimonial.html' %} {% endblock testimonial %}
    <!-- testimonial ends here  -->

    <!-- footer -->
    {% block footer %} {% include 'footer.html' %} {% endblock footer %}
    <!-- footer ends here  -->

home/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en"> 
<head>
    <meta charset="UTF-8"> 
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="keyword" content="{% block 'keywords' %} Home {% endblock 'keywords' %}">
    <meta name="description" content="{% block description %} Home {% endblock description %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">


    <title>{% block title %} Home|prodigious storeapp {% endblock title %}</title>

    
    <link rel="stylesheet" href="{% static '' %}css/day10.css">
    <link rel="icon" type="image/png" sizes="96x96" href="{{setting.icon.url}}">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>Prodigious | Ecommerece store</title>
</head>
<body>
<section class="body">
    <!-- header and banner combinned  -->
    {% block header %} {% endblock header %}
    <!-- header and banner ends combinned  -->

    <!-- pro_header starts  -->
    {% block prod_header %}{% endblock prod_header %}
    <!-- pro_header ends  -->

    <!-- featured categories start here  -->
    {% block content %} {% endblock content %}
    <!-- featured categories ends here  -->

    <!-- offer products  -->
    {% block offer %} {% endblock offer %}
    <!-- offer products ends here  -->

    <!-- testimonial  -->
    {% block testimonial %} {% endblock testimonial %}
    <!-- testimonial ends here  -->

    <!-- brands  -->
    {% block brands %} {% endblock brands %}
    <!-- brands ends here  -->

    <!-- footer -->
    {% block footer %} {% endblock footer %}
    <!-- footer ends here  -->

    <!-- js for togglemenu  -->
    <script src="{% static '' %}js/togglemenu.js"></script>
    <!-- js for togglemenu ends  -->

    <!-- js for gallary  -->
    <script src="{% static '' %}js/gallery.js"></script>
    <!-- js for gallary ends -->

    <!-- js for toggleform  -->
    <script src="{% static '' %}js/toggleform.js"></script>
    <!-- js for toggleform ends  -->
</section>
</body>
</html>

home/templates/brands.html
<div class="brands">
    <div class="small-container">
        <div class="row">
            {% if brands %}
                {% for item  in brands  %}
                    <div class="col-5">
                        <img src="{{item.brands.url}}" alt="">
                    </div>
                {% endfor %}
            {% endif %}
        </div>
    </div>
</div>

home/templates/header.html
{% load static %}
<div class="headermain">
    <div class="container">
        <div class="header">
            <div class="logo">
                <a href="index.html"><img src="{{setting.logo.url}}" alt="Company's logo"></a>
            </div>
            <div class="navbar">
                <ul id="MenuItems">
                    <li><a href="{% url 'index' %}">Home</a></li>
                        <li><a href="{% url 'category' %}">Category</a></li>
                    {% if  user.id is not None %}
                        <li><a href="{% url 'user' %}"><img src="{{profile.image.url}}" style="border-radius: 30px; height: 50px;"></a></li>
                        <li>
                            <a href="{% url 'user' %}">Welcome!
                                {% if request.user.first_name %}
                                    {{request.user.first_name}}
                                {% else %}
                                   {{request.user.username}}
                                {% endif %}   
                            </a>
                        </li>
                        <li><a href="{% url 'logoutfunc' %}">Logout</a></li>
                        <li><a href=""></a>Change password</li>
                        {% else %}
                            <li><a href="{% url 'accountform' %}">Account</a></li>
                        {% endif %}     
                </ul>
            </div>
            <a href="{% url 'order:shopcart' %}"><img src="{{setting.cart_icon.url}}" alt="shop cart" width="30px" height="30px">
                {% if itemcount > 0 %}
                    <span class="badge red 2-depth-1 mr-1">{{itemcount}}</span>
                {% else %}
                    <span class="badge red z-depth-1 mr-1">0</span>
                {% endif %}
            </a>
            <img src="{{setting.menu_icon.url}}" class="menu-icon" onclick="menutoggle()">    
        </div>
    {% if messages  %}
        {% for message in messages  %}
            <div class="alart alart-sucess alart {{message.tags}}" role="alert">
                <button type="button" class="close" data-dismiss="alart" aria-label="close">
                    <span aria-hidden="true">&times;</span>
                </button>
                {{message}}
            </div>
        {% endfor %}
    {% endif %}
        <!-- banner area  -->
        <div class="row">
            <div class="col-2">
                <h1>Give Your Work some <br> Class And Style</h1>
                <p>
                    {{setting.banner_text|safe}}
                </p>
                <a href="" class="btn">Explore Now &#8594;</a>
            </div>
            <div class="col-2">
                <img src="{{banner.image.url}}">
            </div>    
        </div>
    </div>
</div>
<!-- Header and banner done  -->

home/templates/prod_header.html
<!-- header  -->
<div class="headermain">
    <div class="container">
        <div class="header">
            <div class="logo">
                <a href="{% url 'index' %}"><img src="{{setting.logo.url}}" alt="Company's logo"></a>
            </div>
            <div class="navbar">
                <ul id="MenuItems">
                    <li><a href="{% url 'index' %}">Home</a></li>
                        <li><a href="{% url 'category' %}">Category</a></li>
                    {% if  user.id is not None %}
                        <li><a href="{% url 'user' %}"><img src="{{profile.image.url}}" style="border-radius: 30px; height: 50px;"></a></li>
                        <li>
                            welcome <a href="{% url 'user' %}">
                                {% if request.user.first_name %}
                                    <p><strong>{{request.user.first_name}}</strong></p>
                                {% else %}
                                    <p><strong>{{request.user.username}}</strong></p>
                                {% endif %}   
                            </a>
                        </li>
                        <li><a href="{% url 'logoutfunc' %}">Logout</a></li>
                        <li><a href=""></a>Change password</li>
                        {% else %}
                            <li><a href="{% url 'accountform' %}">Account</a></li>
                        {% endif %}     
                </ul>
            </div>
                <a href="{% url 'order:shopcart' %}"><img src="{{setting.cart_icon.url}}" alt="shop cart" width="30px" height="30px">
                    {% if itemcount > 0 %}
                        <span class="badge red 2-depth-1 mr-1">{{itemcount}}</span>
                    {% else %}
                        <span class="badge red z-depth-1 mr-1">0</span>
                    {% endif %}
                </a>
            <img src="{{setting.menu_icon.url" class="menu-icon" onclick="menutoggle()">
        </div>
    {% if messages  %}
        {% for message in messages  %}
            <div class="alart alart-sucess alart {{message.tags}}" role="alert">
                <button type="button" class="close" data-dismiss="alart" aria-label="close">
                    <span aria-hidden="true">&times;</span>
                </button>
                {{message}}
            </div>
        {% endfor %}
    {% endif %}
    </div>
</div>
<!-- header done  -->

home/templates/product-details.html
{% extends 'base.html' %}

{% load humanize %}

{% block title %} {{catdata.title}} {% endblock title %}

{% block keywords %} {{catdata.keywords}} {% endblock keywords %}

{% block description %} {{catdata.description}} {% endblock description %}
    


{% block prod_header %} {% include 'prod_header.html' %}{% endblock prod_header %}

{% block content %}
      <!-- single product details  -->
      <div class="small-container single-product">
        <div class="row">
                <div class="col-2">
                    <img src="{{product.image.url}}" alt="" width="100%" id="ProductImg">
                    <div class="small-img-row">
                        {% if images %}
                           {% for item in images %}
                                <div class="small-img-col">
                                    <img src="{{item.image.url}}" alt="" width="100%" class="SmallImg">
                                </div>
                           {% endfor %} 
                        {% endif %}
                    </div>
                </div>
            
            <div class="col-2">
                <p>{{product.title}}</p>
                <h1>{{product.description}}</h1>
                <h4><span style="color: #ff523b;">{{product.available}}</span></h4>
                <h4>     
                    {% if product.discount_price %}
                        <del>${{product.price | floatformat:3 | intcomma}}</del>
                        <span>${{product.discount_price | floatformat:3 | intcomma}}</span>
                    {% else %}
                        <span>${{product.price | floatformat:3 | intcomma}}</span>    
                    {% endif %}  
                </h4>
                <h4><strong>Available sizes</strong><span style="color: #ff523b;">{{product.sizes}}</span></h4>
                <form action="{% url 'order:addtoshopcart' %}" method="POST">
                    {% csrf_token %}
                    <select name="size">
                        <option value="Small">Small</option>
                        <option value="Medium">Medium</option>
                        <option value="Large">Large</option>
                        <option value="XL">XL</option>
                        <option value="XXL">XXL</option>
                    </select>
                    <label>Qty:</label>
                    <input type="number" name="quantity" value="1" min="{{product.minquantity}}" max="{{product.quantity_instock}}">
                    <button type="submit" class="btn" value="Add to cart">Add to Cart</button>
                    <input type="hidden" name="prodid" value="{{product.id}}">
                </form>
                <h3>product Details <i class="fa fa-indent"></i></h3>
                <br>
                <p>{{product.detail|safe}}</p>
                <!-- <select>
                    <option>Select Size</option>
                    <option>XL</option>
                    <option>Large</option>
                    <option>Medium</option>
                    <option>Small</option>
                </select> -->
                <!-- <input type="number" value="1">
                <a href="cart.html" class="btn">Add To Cart</a>
                <h3>Product Details<i class="fa fa indent"></i></h3>
                <br>
                <p>Shifon down is made of lightweight, stretchy, smooth, fabrics.
                    so silky mixed with satin, lycra, charmcuse, chiffon and lace
                </p> -->
            </div>
        </div>
    </div>

    <!-- title  -->
    <div class="small-container">
        <div class="row row-2">
            <h2>Related Products</h2>
            <a href="{% url 'category' %}" class="btn">View More</a>
        </div>
    </div>

    <!-- Products  -->
    <div class="small-container">
        <div class="row">
            {% if products %}
                {% for item in products %}
                    <div class="col-4">
                        <a href="{% url 'prod_details' item.id item.slug %}"><img src="{{item.image.url}}" alt=""></a>
                        <a href="{% url 'prod_details' item.id item.slug %}"><h4>{{item.title}}</h4></a>
                        <a href="{% url 'prod_details' item.id item.slug %}" class="category">{{item.category}}</a>
                        <div class="ratings">
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star-o"></i>
                        </div>
                        <p class="price">
                            {% if item.discount_price %}
                                <del>#{{item.price | floatformat:2 | intcomma}}</del>
                                <span>#{{item.discount_price | floatformat:2 | intcomma}}</span>
                            {% else %}
                                <span>#{{item.price | floatformat:2 | intcomma}}</span>                                
                            {% endif %}           
                        </p>
                    </div>
                {% endfor %}
            {% endif %}
        </div>
    </div>
<!-- product details end here  -->
{% endblock content %}









     <!-- footer -->
     <div class="footer">
        <div class="container">
            <div class="row">
                <div class="footer-col-1">
                    <h3>Vist our store</h3>
                    <p>Be assured of exciting shopping Expreience</p>
                </div>
                <div class="footer-col-2">
                    <img src="images/pro.png" alt="">
                    <p>We have top quality Products at best prices</p>
                </div>
                <div class="footer-col-3">
                    <ul>
                        <li><a href="index.html">Home Page</a></li>
                        <li><a href="about.html">About Page</a></li>
                        <li><a href="contact.html">Contact Us</a></li>
                        <li><a href="cart.html">Your cart</a></li>
                    </ul>
                </div>
                <div class="footer-col-4">
                    <ul>
                        <li><a href="">Facebook</a></li>
                        <li><a href="">Instagram</a></li>
                        <li><a href="">Twitter</a></li>
                        <li><a href="">Whatsapp</a></li>
                    </ul>
                </div>
            </div>
            <hr>
            <p class="copyright">Copyright 2021 &copy; prodigious stores</p>
        </div>
    </div>
    <!-- footer ends here  -->

    <!-- js for togglemenu  -->
    <script src="js/togglemenu.js"></script>
    <!-- js for product gallery  -->
    <script src="js/gallery.js"></script>
    <!-- js for product gallery done  -->
</body>
</html>

home/templates/product.html
{% extends 'base.html' %}

{% load humanize %}

{% block title %} {{catdata.title}} {% endblock title %}

{% block keywords %} {{catdata.keywords}} {% endblock keywords %}

{% block description %} {{catdata.description}} {% endblock description %}
    


{% block prod_header %} {% include 'prod_header.html' %}{% endblock prod_header %}


{% block content %}
    <div class="small-container">
        <div class="row row-2">
            <h2>All {{product.category}} Products</h2>
        </div>
        <div class="row">
            {% if products %}
                {% for item in products %}
                    <div class="col-4">
                        <a href="{% url 'prod_details' item.id item.slug %}"><img src="{{item.image.url}}" alt=""></a>
                        <a href="{% url 'prod_details' item.id item.slug %}"><h4>{{item.title}}</h4></a>
                        <a href="{% url 'prod_details' item.id item.slug %}" class="category">{{item.category}}</a>
                        <div class="ratings">
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star-o"></i>
                        </div>
                        <p class="price">
                            {% if item.discount_price %}
                                <del>#{{item.price | floatformat:2 | intcomma}}</del>
                                <span>#{{item.discount_price | floatformat:2 | intcomma}}</span>
                            {% else %}
                                <span>#{{item.price | floatformat:2 | intcomma}}</span>                                
                            {% endif %}      
                        </p>
                        <form action="{% url 'order:addtoshopcart' %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="quantity" class="span1" value="1">
                            <button class="butons" type="submit">Add to cart</button>
                            <input type="hidden" name="prodid" value="{{item.id}}">
                        </form>
                    </div>
                {% endfor %}
            {% endif %}
        </div>
        <div class="page-buttons">
            {% if products.has_other_pages  %}
                {% if products.has_previous %}
                    <a href="?page={{products.previous_page_number}}">&laquo;</a>
                {% else %}
                <span><a>&laquo;</a></span>
                {% endif %}
                   {% for item in products.paginator.page_range %}
                        {% if products.number == item %}
                            <span>
                                <a>{{item}}</a>
                            </span>
                        {% else %}
                        <span>
                            <a href="?page={{item}}">{{item}}</a>
                        </span>
                        {% endif %}
                   {% endfor %} 
                   {% if products.has_next %}
                       <a href="?page={{products.next_page_number}}">&raquo;</a>
                    {% else %}
                        <span><a>&raquo;</a></span>
                   {% endif %}       
            {% endif %}    
        </div>
    </div>
{% endblock content %}

{% block footer %} {% include 'footer.html' %}{% endblock footer %}