home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.index,name=('index')),
    path('about/',views.about,name=('about')),
    path('contact/',views.contact,name=('contact')),

    path('category/',views.category,name='category'),
    path('product/<str:id>/<slug:slug>',views.product_list,name='product_list'),
    path('product-details/<str:id>/<slug:slug>',views.product_details,name='prod_details')
]

order/urls.py
from django.urls import path 
from . import views


app_name = 'order'

urlpatterns = [
    path('',views.order,name='order'),
    path('addtoshopcart/',views.addtoshopcart,name='addtoshopcart'),
    path('shopcart/',views.shopcart,name='shopcart'),
    path('updatequantity/',views.updatequantity,name='updatequantity'),
    path('deletefromcart/<str:id>',views.deletefromcart,name='deletefromcart'),
    path('checkout/',views.checkout,name='checkout'),
    path('placeorder/',views.placeorder,name='placeorder'),
    path('ordercompleted/',views.ordercompleted,name='ordercompleted')
]

prodigiousapp/urls.py
from user.forms import RegisterForm
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static

from user import views as UserViews
urlpatterns = [
    path('',include('home.urls')),
    path('product/',include('product.urls')),
    path('user/',include('user.urls')),
    path('accountform/', UserViews.accountform, name='accountform'),
    path('login/', UserViews.loginform, name='loginform'),
    path('logout/', UserViews.logoutfunc,name='logoutfunc'),
    path('register/', UserViews.registerform,name='registerform'),
    path('update/', UserViews.userupdate, name='userupdate'),
    path('password/', UserViews.userpassword,name='userpassword'),
    path('order/',include('order.urls')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/models.py
from django.db import models
from django.contrib.auth.models import User
# from django.forms import NumberInput, Select

from django.forms import ModelForm
from product.models import Product
from django.forms import Select
# Create your models here.

class ShopCart(models.Model):
    user = models.ForeignKey(User,on_delete=models.SET_NULL,null=True)
    product = models.ForeignKey(Product,on_delete=models.SET_NULL,null=True,blank=True)
    quantity = models.IntegerField(blank=True, null=True)
    order_placed = models.BooleanField(default=False)
    # size = models.CharField(max_length=100,choices=SIZE, blank=True, null=True)
    size = models.CharField(max_length=10,blank=True, null=True)
    order_code = models.CharField(max_length=70, editable=False)

    

    @property
    def price(self):
        if self.product_id is not None:
            return (self.product.price)

    
    @property
    def amount(self):
        if self.product_id is None:
            return (None)
        else:
            if self.product.discount_price:
                return(self.product.discount_price * self.quantity)
            else:
                return(self.product.price * self.quantity)


class ShopCartForm(ModelForm):
    class Meta:
        model = ShopCart
        fields = ['quantity','size']


class Order(models.Model):
    STATUS=(
        ('New','New'),
        ('Accepted','Accepted'),
        ('preparing','prepating'),
        ('Onshipping','Onshipping'),
        ('completed','completed'),
        ('canceled','canceled'),
    )
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    total = models.FloatField(blank=True, null=True)
    order_placed = models.BooleanField(default=False)
    order_code = models.CharField(max_length=70, editable=False)
    payment_code = models.CharField(max_length=8, editable=False)
    first_name = models.CharField(max_length=15)
    last_name = models.CharField(max_length=15)
    phone = models.CharField(blank=True, null=True,max_length=20)
    address = models.CharField(max_length=150,blank=True, null=True)
    city = models.CharField(blank=True,max_length=150)
    state = models.CharField(blank=True, null=True, max_length=20)
    country = models.CharField(blank=True, max_length=20)
    adminnote = models.CharField(blank=True, null=True, max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    
    

class OrderForm(ModelForm):
    class Meta:
        model= Order
        fields = ['first_name','last_name','address','phone','city','country']

order/views.py
from math import prod
from django.conf.urls import url
from django.http.response import HttpResponse
from django.shortcuts import redirect, render
from django.http import HttpResponse, request

from django.contrib import messages 
from home.models import Setting
from product.models import *
from . models import *
from user.models import *
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
import requests
import json
import random
import string
import uuid
from django.views.decorators.http import require_POST


# Create your views here.

def order(request):
    return HttpResponse('order page')


@require_POST
@login_required(login_url='/login')
def addtoshopcart(request):
    url = request.META.get('HTTP_REFERER')
    thequantity = int(request.POST['quantity'])
    thesize = request.POST.get('size',None)
    theprodid = request.POST['prodid']
    aprod = Product.objects.get(pk=theprodid)

    # check if the user has an existing cart 
    cart = ShopCart.objects.filter(order_placed=False).filter(user__username = request.user.username)

    if cart: #on existing cart is noticed 
        prodchecker = ShopCart.objects.filter(product_id = aprod.id, size=thesize, quantity=thequantity,user__username = request.user.username).first()

        if prodchecker: #product exists in the cart, increment it 
            prodchecker.quantity += thequantity
            prodchecker.size = thesize
            prodchecker.save()
            messages.success(request,'Product added to Shopcart')
            return redirect(url)

        else: #products is not in the cart, add it
            anitem = ShopCart()
            anitem.product=aprod
            anitem.user=request.user
            anitem.order_code=cart[0].order_code
            anitem.quantity=thequantity
            anitem.size=thesize
            anitem.order_placed=False
            anitem.save()

    
    else: #create a new cart,generate order code
        ordercode = str(uuid.uuid4())
        newcart = ShopCart()
        newcart.product=aprod
        newcart.user=request.user
        newcart.order_code=ordercode
        newcart.quantity=thequantity
        newcart.size = thesize
        newcart.order_placed=False
        newcart.save()

    messages.success(request,"product added to Shopcart")

    return redirect(url)



@login_required(login_url='/login')
def shopcart(request):
    category = Category.objects.all()
    setting = Setting.objects.get(pk=1)
    shopcart = ShopCart.objects.filter(order_placed=False).filter(user__username=request.user.username)

    subtotal=0
    shippingfee=0
    vat =0
    total = 0

    for item in shopcart:
        if item.product.discount_price:
            subtotal += item.product.discount_price * item.quantity
        else:
            subtotal += item.product.price * item.quantity

    # shipping rules: 0% fees to all orders above 150, 0 fees to orders lower
    if subtotal > 150:
        shippingfee = 0.08 * subtotal 
    else:
        shippingfee =0 
    vat = 0.075 * subtotal 

    total = subtotal + shippingfee + vat 

    context={
        'setting':setting,
        'category':category,
        'shopcart':shopcart,
        'subtotal':subtotal,
        'shipping':shippingfee,
        'vat':vat,
        'total':total
    }
    return render(request,'shopcart.html',context)


@require_POST
@login_required(login_url='/login')
def updatequantity(request):
    url = request.META.get('HTTP_REFERER')
    newquantity = request.POST['itemquantity']
    theitem = ShopCart.objects.get(id=request.POST['itemid'])
    theitem.quantity = newquantity
    theitem.save()

    messages.success(request,"product Quantity sucessfully updated")
    return redirect(url)


@login_required(login_url='/login')
def deletefromcart(request,id):
    ShopCart.objects.filter(id=id).delete()
    messages.success(request,'Item deleted from Shopcart')
    return redirect('order:shopcart')


@login_required(login_url='/login')
def checkout(request):
    category = Category.objects.all()
    setting = Setting.objects.get(pk=1)
    shopcart = ShopCart.objects.filter(user__username = request.user.username).filter(order_placed=False)
    profile = UserProfile.objects.get(user__username = request.user.username)

    subtotal = 0
    shippingfee = 0
    vat = 0
    total = 0

    for item in shopcart:
        if item.product.discount_price:
            subtotal += item.product.discount_price * item.quantity 
        else:
            subtotal += item.product.price * item.quantity 

    # shipping rules: 8% fees to all orders above 150.0 fees to oreder lower 
    if subtotal > 150:
        shippingfee = 0.08 * subtotal 
    else:
        shippingfee = 0 

    # vat is at 7.50% of the total purchase to be made 
    vat = 0.075 * subtotal 

    total = subtotal + shippingfee + vat 

    context ={
        'setting':setting,
        'shopcart':shopcart,
        'order_code':shopcart[0].order_code,
        'profile':profile,
        'category':category,
        'subtotal':subtotal,
        'shipping':shippingfee,
        'vat':vat,
        'total':total 
    }
    return render(request,'checkout.html',context)





@require_POST
@login_required(login_url='/login')
def placeorder(request):
    api_key = 'sk_test_a531e70ae7fc4a7eaa53bb1004ae731b4e854033'
    url = 'https://api.paystack.co/transaction/initialize'
    callback_url = 'http://18.118.18.73/order/ordercompleted/'
    ordercode = request.POST['order_number']
    autogen_ref = ''.join(random.choices(string.digits + string.ascii_letters, k=8))
    current_user = User.objects.get(username = request.user.username)
    user = UserProfile.objects.get(user_id = current_user.id)
    total = float(request.POST['amount']) * 100

    headers = {'Authorization': f'Bearer {api_key}'}
    data = {'reference': autogen_ref, 'amount': int(total), "currency": "NGN", 'order_number':ordercode, 'email':user.email, 'callback_url':callback_url}

    #making a request to PAYSTACK
    try:
        r =requests.post(url, headers=headers, json=data)
    except Exception:
        messages.error(request, "Network busy. Please try again in few minutes. Thank You")
    else:
        #create an order
        transback = json.loads(r.text)

        rd_url = transback['data']['authorization_url']
        theuser = UserProfile.objects.filter(user=request.user).first()
        order = Order()
        order.first_name=theuser.user.first_name
        order.last_name=theuser.user.last_name 
        order.phone=theuser.phone
        order.city=theuser.city
        order.order_code=ordercode
        order.payment_code = autogen_ref
        order.total=total
        order.order_placed = True
        order.save()
        return redirect(rd_url) 
    return redirect('order:checkout')

@login_required(login_url='/login')
def ordercompleted(request):
    category = Category.objects.all()
    setting = Setting.objects.get(pk=1)
    banner = Product.objects.get(banner=True)
    offer = Product.objects.get(offer=True)
    profile = UserProfile.objects.get(user__username = request.user.username)
    shopcart = ShopCart.objects.filter(order_placed=False).filter(user__username = request.user.username)

    # cleaning the shopcart 
    for item in shopcart:
        item.order_placed = True
        item.save()

        # reducing Quantity instock 
        aproduct = Product.objects.get(id=item.product.id)
        aproduct.quantity_instock -= item.quantity
        aproduct.save()

    context ={
        'setting':setting,
        'offer':offer,
        'category':category,
        'shopcart':shopcart,
        'profile':profile,
    }
    return render(request,'ordercompleted.html',context)

order/templates/checkout.html
{% extends 'base.html' %}

{% load humanize %}


{% block title %} Checkout {% endblock title %}

{% block keywords %} {{setting.keywords}} {% endblock keywords %}

{% block description %} {{setting.description}}{% endblock description %}


<!-- Header starts  -->
{% block header %} {% include 'prod_header.html' %} {% endblock header %}
<!-- Header ends  -->


{% block content %}
    <!-- checkout page  -->
    <div class="checkout-page" style="padding: 50px 0;">
        <h2 class="title">Checkout Page</h2>
        <div class="container">
            <div class="row">
                <div class="col-2">
                    <div class="form container" style="height: 520px;">
                        <div class="form-buttons">
                            <h4 class="title"><strong>Order</strong>Details</h4>
                        </div>
                        <form action="{% url 'order:placeorder' %}" method="POST">
                        {% csrf_token %}
                            <input type="text" value="{{profile.first_name}}" placeholder="first Name">
                            <input type="text" value="{{profile.last_name}}" placeholder="last Name">
                            <input type="text" value="{{profile.phone}}" placeholder="Phone Number">
                            <input type="text" value="{{profile.address}}" placeholder="Address">
                            <input type="text" value="{{profile.city}}" placeholder="city">
                            <input type="text" value="{{profile.state}}" placeholder="State">
                            <input type="text" value="{{profile.country}}" placeholder="Country">
                            <input type="hidden" name="amount" value="{{total}}">
                            <input type="hidden" name="order_number" value="{{order_code}}">
                            <button type="submit" class="buttons">Proceed To Order</button>
                        </form>
                    </div>
                </div>
                <div class="col-2">
                    <div class="small-container cart-page" style="height: 520px; width:520px">
                        <div class="form buttons">
                            {% if messages  %}
                                {% for message in messages %}
                                    <div class="alart alart-success alart-{{message.tags}}" role="alert">
                                        <button type="button" class="close" data-dismiss="alart" aria-label="close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                        {{message|safe }}
                                    </div>
                                {% endfor %}
                            {% endif %}
                        </div>
                        <h4 class="title" style="text-align: center">Delivery Details</h4>
                        <table>
                            <tr>
                                <th>Product</th>
                                <th>Quantity</th>
                                <th>Size</th>
                                <th>Amount</th>
                            </tr>
                            {% if shopcart  %}
                                {% for item in shopcart %}
                                    <tr>
                                        <td>
                                            <div class="cart-info">
                                                <div>
                                                    <p>{{item.product.title}}</p>
                                                </div>
                                            </div>    
                                        </td>
                                        <td>{{item.quantity}}</td>
                                        <td>{{item.size}}</td>
                                        <td>{{item.amount | floatformat:2 | intcomma}}</td>
                                    </tr>
                                {% endfor %}
                            {% endif %}
                        </table>
                        <div class="total-price">
                            <table>
                                <tr>
                                    <td>Total</td>
                                    <td>#{{total | floatformat:2 | intcomma}}</td>
                                </tr>
                            </table>
                        </div>
                    </div> 
                </div>
            </div>
        </div>
    </div>
{% endblock content %}
         
{% block footer %} {% include 'footer.html' %}{% endblock footer %}
    <!-- js for togglemenu  -->
    <script src="js/togglemenu.js"></script>

order/templates/ordercompleted.html
{% extends 'base.html' %}
{% load static %}

{% block title %} order completed {% endblock title %}

{% block keywords %} {{product.keywords}} {% endblock keywords %}

{% block description %} {{product.description}}{% endblock description %}


<!-- Header and banner  -->
{% block header %} {% include 'acheader.html' %} {% endblock header %}
<!-- Header and banner done  -->

{% block content %}
    <!-- Account page  -->
    <div class="account-page">
        <div class="container">
            <div class="row">
                <div class="col-2">
                    <div class="uform container">
                        <h4>Dear <span style="color: #ff523b;">{{profile.user.username}} {{profile.user.last_name}}</span></h4>
                        <h5>Your order is completed</h5>
                        <p>Thank You for your patronage</p>
                    </div>
                </div>
                <div class="col-2">
                    <div class="row">
                        <div class="col-2">
                            <img src="{{offer.image.url}}" class="offer img">
                        </div>
                    </div>
                </div>
                <div class="col-2">
                    <p>Esclusively availabable at prodigious store</p>
                    <h1>Lingerie</h1>
                    <small>
                        Our range of woman's Lingerie is a must have in any underwear drawer.
                        so, get ready to impress while you underess with the best range of lingeries.
                    </small>
                    <a href="{% url 'category' %}" class="buttons">Buy Now &#8594;</a>
                </div>
            </div>
        </div>
    </div>
    <!-- Account page done  -->
{% endblock content %}

{% block footer %} {% include 'footer.html' %} {% endblock footer %}

order/templates/shopcart.html
{% extends 'base.html' %}

{% load humanize %}


{% block title %} Shopcart {% endblock title %}

{% block keywords %} {{product.keywords}} {% endblock keywords %}

{% block description %} {{product.description}}{% endblock description %}


<!-- Header starts  -->
{% block header %} {% include 'prod_header.html' %} {% endblock header %}
<!-- Header ends  -->
    
    <!-- cart items details  -->
{% block content %}
    <div class="small-container cart-page">
        <table>
            <tr>
                <th>Product</th>
                <th>Quantity</th>
                <th>Size</th>
                <th>Amount</th>
            </tr>
            {% if shopcart  %}
                {% for item in shopcart %}
                    <tr>
                        <td>
                            <div class="cart-info">
                                <img src="{{item.product.image.url}}" alt="">
                                <div>
                                    <p>{{item.product.title}}</p>
                                    <small>
                                        {% if item.discount_price %}
                                            {{item.discount_price | floatformat:2 | intcomma}}
                                        {% else %}
                                            {{item.discount | floatformat:2 | intcomma}}
                                        {% endif %}  
                                    </small>
                                    <br>
                                    <a href="{% url 'order:deletefromcart' item.id %}">Remove</a>
                                    <form action="{% url 'order:updatequantity' %}" method="POST">
                                    {% csrf_token %}
                                        <input style="width: 70px; height:20px" type="item" name="itemquantity" value="{{item.quantity}}" min="{{item.product.minquantity}}" max="{{item.product.quantity_instock}}">
                                        <button type="submit" style="color:#ff523b;font-size:12px;border:none;outline:none">update Quantity</button>
                                        <input type="hidden" name="itemid" value="{{item.id}}">
                                    </form>
                                </div>
                            </div>    
                        </td>
                        <td>{{item.quantity}}</td>
                        <td>{{item.size}}</td>
                        <td>{{item.amount | floatformat:2 | intcomma}}</td>
                    </tr>
                {% endfor %}
            {% endif %}
                
            
            <!-- <tr>
                <td>
                    <div class="cart-info">
                        <img src="images/ladies/1.jpg" alt="">
                        <div>
                            <p>Wrangler Topskirt</p>
                            <small>Price: 15,000</small>
                            <br>
                            <a href="">Remove</a>
                        </div>
                    </div>
                </td>
                <td><input type="number" value="1"></td>
                <td>15,000</td>
            </tr> -->
            <!-- <tr>
                <td>
                    <div class="cart-info">
                        <img src="images/ladies/3.jpg" alt="">
                        <div>
                            <p>Wrangler Topskirt</p>
                            <small>Price: 15,000</small>
                            <br>
                            <a href="">Remove</a>
                        </div>
                    </div>
                </td>
                <td><input type="number" value="1"></td>
                <td>15,000</td>
            </tr> -->
            <!-- <tr>
                <td>
                    <div class="cart-info">
                        <img src="images/ladies/4.jpg" alt="">
                        <div>
                            <p>Wrangler Topskirt</p>
                            <small>Price: 15,000</small>
                            <br>
                            <a href="">Remove</a>
                        </div>
                    </div>
                </td>
                <td><input type="number" value="1"></td>
                <td>15,000</td>
            </tr> -->
        </table>
        <div class="total-price">
            <table>
                <tr>
                    <td>Subtotal</td>
                    <td>{{subtotal | floatformat:2 | intcomma}}</td>
                </tr>
                <tr>
                    <td>Shipping</td>
                    <td>{{Shipping | floatformat:2 | intcomma}}</td>
                </tr>
                <tr>
                    <td>vat(7.50%)</td>
                    <td>{{vat | floatformat:2 | intcomma}}</td>
                </tr>
                <tr>
                    <td>Total</td>
                    <td>#{{total | floatformat:2 | intcomma}}</td>
                </tr>
            </table>
        </div>
        <div class="total-price">
            <table>
                <tr>
                    <td><a href="{% url 'category' %}" class="btn">Continue</a></td>
                    <td><a href="{% url 'order:checkout' %}" class="btn">Checkout</a></td>
                </tr>
            </table>
        </div>
    </div>
{% endblock content %}
    
    <!-- footer -->
     {% block footer %} {% include 'footer.html' %}{% endblock footer %}
    <!-- footer ends here  -->

    <!-- js for togglemenu starts  -->
    <script src="js/togglemenu.js"></script>
    <!-- js for togglemenu ends  -->
</body>
</html>